const apiData = [
    {
        "id": 1,
        "intervieweeLocation": "Canberra, District of Canberra Central, Australian Capital Territory, 2601, Australia",
        "date": "2020-07-04",
        "escapeCountry": "Russia",
        "transgender": 0,
        "intervieweeId": 1,
        "interviewerId": 1,
        "isCitizen": 0,
        "pseudonym": 0,
        "videoDistortion": 0,
        "voiceChange": 0,
        "contextual": "I met Elena Nechaeva in January 2018. <br/> She was a part of the PhD research conducted by my partner Tina Dixson. I was a part of this research as well. Tina Dixson looked at the lived experiences of queer refugee women* through the lens of trauma.  At that time 8 women participated in the research who were spread around Australia (NSW, ACT, VIC). At the end of Tina’s fieldwork, we ran a fundraising campaign to organise a retreat and bring together all of us to meet for the first time. We were able to rent a house, pay for tickets, rent a car and pay for food. We spent 3 days together at the South Coast of NSW. Through these days we worked and then we had a lot of fun together. Later in 2018, we all marched on the 40th anniversary of the Sydney Gay and Lesbian Mardi Gras. This was the first LGBTIQ parade for Elena.\r\nIn 2019 Tina Dixson and I organised the first conference in Australia dedicated to issues of LGBTIQ forced displaced titled ‘Queer Displacements: Sexuality, Migration & Exile’.  It was held at the Australian National University. Elena came to this conference and actively participated. Through this conference, she knew that I am creating an archive as a part of my PhD research. She said that she wanted to contribute her story as she wanted to ensure that lesbian voices were recorded and represented.  She said that she wanted to use her real name and do this recording as a video interview.  I responded that we needed more time to talk with her about this because here safety was important.  I also asked her to think about how she would think about this interview in 5 years’ time because it would be an open access that everyone could see. She was emotional and quite affirmative that she didn't want to hide anymore in her life. This conversation took place in November 2019. I said that we need to come back to this conversation later again. \r\nIn April 2020 Tina Dixson, Elena Nechaeva, Lavanya Kala and I registered the first LGBTIQ refugee organisation called Forcibly Displaced People Network to work across Australia and the Asia Pacific. Elena was appointed to be a Treasurer. We started communicating with Elena more often as Board directors. As the Treasurer of the organisation she planned to come to Canberra (ACT) to discuss work-related issues. Our conversation to contribute her oral history to the archive came up again and we agreed that we would record her interview while she was here. \r\nShe came to our house on the 3rd of July 2020. On the 4th of July 2020 after breakfast, I set up my camera in our lounge room. After discussing again the research safety considerations, Elena signed all needed documentation and we proceeded with an interview. \r\nBefore the interview, I asked her how she wanted me to act if she would be upset and started crying. She said that giving an interview in the English language would help her distance herself from her emotions. “I doubt that I will cry” Elena said. \r\nOn the 12th of August 2020, I sent her a draft of our interview. I asked Elena to review it and tell me if she wanted to add anything or delete it from this interview. On the 13th of August, she replied to my email with: “This is funny. :) Go ahead with this”\r\nAfter five years of waiting for her visa outcome in August 2020 Elena and her partner were granted permanent protection visa from the Australian government.",
        "refugeeCamp": 1,
        "published": 1,
        "accessionName": "AQDA_2020-07-04_0004_AS_AU",
        "migrationId": 1,
        "lat": "-35.2975906",
        "lng": "149.1012676",
        "genderId": 1,
        "narratorNameD": "Elena Nechaeva",
        "docLink": "",
        "languageId": 1,
        "image": "/aqda/frontend/web/index.php?r=interview/showimage&id=1",
        "narrator": {
            "id": 1,
            "name": "Elena Nechaeva",
            "birthYear": "1969"
        },
        "interviewer": {
            "id": 1,
            "name": "Renee Dixson",
            "bio": ""
        },
        "migration": {
            "id": 1,
            "name": "Asylum seeker"
        },
        "language": {
            "id": 1,
            "name": "English"
        },
        "pronouns": "She/Her/Hers",
        "sexo": "Lesbian",
        "gender": {
            "id": 1,
            "name": "Female"
        },
        "publishMedia": [
            {
                "id": 1,
                "accessName": "AQDA_2020-07-04_0004_AS_AU-A",
                "status": 1,
                "accessionDate": "2007-01-22",
                "youtubeUrl": "https://youtu.be/W5CqYNx_iSs",
                "interviewId": 1,
                "mediaType": 1,
                "size": 11070,
                "length": 5706,
                "youtubeDes": "test",
                "lengthText": "01:35:06",
                "storages": [
                    {
                        "id": 1,
                        "accessName": "AQDA_2020-07-04_0004_AS_AU-A",
                        "storageType": 2,
                        "size": 1169,
                        "location": "",
                        "length": 239,
                        "createTime": null,
                        "equipment": "",
                        "uncompressedSize": null,
                        "noOfFiles": null,
                        "fileName": "",
                        "mediaId": 1,
                        "notes": "",
                        "lengthText": "00:03:59"
                    },
                    {
                        "id": 2,
                        "accessName": "AQDA_2020-07-20_0004_AS_AU_AP",
                        "storageType": 1,
                        "size": null,
                        "location": "",
                        "length": 3659,
                        "createTime": null,
                        "equipment": "",
                        "uncompressedSize": null,
                        "noOfFiles": null,
                        "fileName": "",
                        "mediaId": 1,
                        "notes": "",
                        "lengthText": null
                    },
                    {
                        "id": 3,
                        "accessName": "AQDA_2020-07-22_0004_AS_AU_AP",
                        "storageType": 1,
                        "size": null,
                        "location": "",
                        "length": 0,
                        "createTime": null,
                        "equipment": "",
                        "uncompressedSize": null,
                        "noOfFiles": null,
                        "fileName": "",
                        "mediaId": 1,
                        "notes": "",
                        "lengthText": null
                    }
                ],
                "transcriptions": []
            },
            {
                "id": 3,
                "accessName": "AQDA_2020-07-20_0004_AS_AU-P",
                "status": 0,
                "accessionDate": "2022-01-22",
                "youtubeUrl": "https://youtu.be/W5CqYNx_iSs",
                "interviewId": 1,
                "mediaType": 1,
                "size": 75570,
                "length": 5766,
                "youtubeDes": "",
                "lengthText": "01:36:06",
                "storages": [],
                "transcriptions": []
            }
        ]
    },
    {
        "id": 2,
        "intervieweeLocation": "Bochum",
        "date": "2019-06-21",
        "escapeCountry": "Bangladesh",
        "transgender": 0,
        "intervieweeId": 2,
        "interviewerId": 1,
        "isCitizen": 0,
        "pseudonym": 1,
        "videoDistortion": 1,
        "voiceChange": 0,
        "contextual": "On the 20th of May 2019 I contacted Rosa Strippe e.V. Projekt \"Senlima\" in Bochum. On the 18th of June 2019, I met with Nicky Ulrich, coordinator of the group for LGBTIQ refugees. We had a conversation about my research. Later that day, they ran a group. Many forcibly displaced people attended. \r\n\r\nNicky said that they wanted to protect and support the group as much as they could. Nicky introduced me to Salman Adeel (name changed), who came to that gathering and called Shylova Kateryna (Vald) to ask if they were interested in talking to me. \r\nSalman Adeel and I talked about my research and its goals. He showed interest to contribute his story to the archive. I asked if we could do it another day so he could have more time to think. We agreed on the day for a potential interview on the 21 of June 2019. I explained to him that it would be ok if he changed his mind. If this was the case, he would send me a message, and it would be an absolutely fine situation. \r\nOn the 21 of June 2019 I came to the office of Rosa Strippe. I was there between 14.00 to 17.00. I came earlier to set up the camera for an interview. At 14.00 Salman wasn’t there. I gave another 10 minutes and messaged his number. After another 10 minutes I called but Salman was out of range. I began to think that he dropped out. After another 10 minutes he showed up. He apologised that he was late because of the train delay and he didn’t have a phone credit to inform me. \r\nWe went through the research forms and talked a lot about safety and the proses of interview. After he signed forms, we started recording the interview. I had quite a limited time as I booked another interview with Vald in several hours. Salman walked with me to the train station and insisted that we had a coffee. We went into bakery at the Bochum train station, ordered coffee and shared a croissant. We continued to chat about the life and future plans. Salman said that he was happy and that he considered himself as a German.    \r\nWe took a selfie and hugged each other before my departure.  \r\nOn the 24 of June 2019 Salman contacted me to ask if I could change his name. After I confirmed that I changed it in my records he sent me another massage asking “Okay thank you and pls when u uploud can u Cover my Face pls for my safty” . I confirmed that I would do it.  Salman replied “Uaowww am very happy ,thank u sooooo much”\r\n\r\nIn August 2020 I contacted Salman to send the interview for review.\r\nHe approved this video for publishing.  ",
        "refugeeCamp": 1,
        "published": 1,
        "accessionName": "AQDA_2019-06-21_0001_AS_DE",
        "migrationId": 1,
        "lat": "51.481810515561335",
        "lng": "7.220420837402345",
        "genderId": 2,
        "narratorNameD": "Salman Adeel",
        "docLink": "",
        "languageId": 1,
        "image": "/aqda/frontend/web/index.php?r=interview/showimage&id=2",
        "narrator": {
            "id": 2,
            "name": "Salman Adeel",
            "birthYear": "1987"
        },
        "interviewer": {
            "id": 1,
            "name": "Renee Dixson",
            "bio": ""
        },
        "migration": {
            "id": 1,
            "name": "Asylum seeker"
        },
        "language": {
            "id": 1,
            "name": "English"
        },
        "pronouns": "He/Him/His",
        "sexo": "Gay",
        "gender": {
            "id": 2,
            "name": "Male"
        },
        "publishMedia": [
            {
                "id": 2,
                "accessName": "AQDA_2019-06-21_0001_AS_DE-A",
                "status": 1,
                "accessionDate": "2020-10-21",
                "youtubeUrl": "https://youtu.be/ua6yK1zlT3A",
                "interviewId": 2,
                "mediaType": 1,
                "size": 5790,
                "length": 4490,
                "youtubeDes": "",
                "lengthText": "01:14:50",
                "storages": [],
                "transcriptions": [
                    {
                        "id": 49,
                        "timestamp": 2,
                        "segmentTitle": "Personal background",
                        "partialTranscription": "Could you please tell me about your background?",
                        "keywords": "Bangladesh; Germany; Middle East; Iraq; Father; Protection; Safety; Turkey; Europe; Boat; Syria; Sexual orientation; Gay; Homosexual",
                        "subject": "test5",
                        "synopsis": "test0",
                        "gps": "33.8496¡ S, 151.2140¡ E",
                        "mediaId": 2,
                        "timestampText": "00:00:02"
                    },
                    {
                        "id": 50,
                        "timestamp": 63,
                        "segmentTitle": "Childhood",
                        "partialTranscription": "You said that your father could not protect you every time, and you do not feel safe. Could you tell more about this?",
                        "keywords": "Girls; Friend; Different; This way; Tenth grade; Boyfriend; gay; Sister; Religious family; Pressure;",
                        "subject": null,
                        "synopsis": null,
                        "gps": null,
                        "mediaId": 2,
                        "timestampText": "00:01:03"
                    },
                    {
                        "id": 51,
                        "timestamp": 270,
                        "segmentTitle": "Coming out",
                        "partialTranscription": "What do you remember about how your friends and parents reacted to your coming out?",
                        "keywords": "Religious family; Pressure; Domestic and family violence; No protection; Pressure; Marriage; Control; Earring; Clothes; Stigma; Love; Social Media;",
                        "subject": null,
                        "synopsis": null,
                        "gps": null,
                        "mediaId": 2,
                        "timestampText": "00:04:30"
                    },
                    {
                        "id": 52,
                        "timestamp": 840,
                        "segmentTitle": "First relationship",
                        "partialTranscription": "Your first boyfriend happened when you were in the 10th grade?",
                        "keywords": "Fourteen years, Naughty, hugs, Family; Beating; Threats; Not safe;",
                        "subject": null,
                        "synopsis": null,
                        "gps": null,
                        "mediaId": 2,
                        "timestampText": "00:14:00"
                    },
                    {
                        "id": 53,
                        "timestamp": 1025,
                        "segmentTitle": "LGBTIQ community",
                        "partialTranscription": "Did you have any organizations that worked with LGBTIQ community back where you lived?",
                        "keywords": "Young; School; Stress; LGBT; Not safe; Unknown man; Left country, India; Pakistan; Iran; Turkey; Iraq; Travel; Friend, Organisation; Help;",
                        "subject": null,
                        "synopsis": null,
                        "gps": null,
                        "mediaId": 2,
                        "timestampText": "00:17:05"
                    },
                    {
                        "id": 54,
                        "timestamp": 1342,
                        "segmentTitle": "LGBTIQ community in Germany",
                        "partialTranscription": "Were you active in the LGBTIQ movement?",
                        "keywords": "Help; Minority; Homophobia; LGBT; Support; Freedom; Government, Problems, Solutions;",
                        "subject": null,
                        "synopsis": null,
                        "gps": null,
                        "mediaId": 2,
                        "timestampText": "00:22:22"
                    },
                    {
                        "id": 55,
                        "timestamp": 1570,
                        "segmentTitle": "LGBTIQ community in Bangladesh",
                        "partialTranscription": "You were not involved in activism in Bangladesh?",
                        "keywords": "Violence; Verbal abuse; Friends; Community; Terrorist; Killed; Xulhaz Mannan;  LGBT activist;",
                        "subject": null,
                        "synopsis": null,
                        "gps": null,
                        "mediaId": 2,
                        "timestampText": "00:26:10"
                    },
                    {
                        "id": 56,
                        "timestamp": 1785,
                        "segmentTitle": "Relationship with family",
                        "partialTranscription": "Did you have the last event that you said to yourself  that is it. I cannot take more of life like this, I am leaving",
                        "keywords": "Uncle; Threats; Physical violence; Move on; Rejection; Discrimination; Sister; Relationship; Mental health; neighbours; aggressive; Leave",
                        "subject": null,
                        "synopsis": null,
                        "gps": null,
                        "mediaId": 2,
                        "timestampText": "00:29:45"
                    },
                    {
                        "id": 57,
                        "timestamp": 2076,
                        "segmentTitle": "Escape from country",
                        "partialTranscription": "How did you end up in Germany?",
                        "keywords": "Plan; Father; Support; Iraq; Like a person; Alone; Cousin; Turkey; Germany; Walk; Boat; Syrian people; Greece; Hunger;",
                        "subject": null,
                        "synopsis": null,
                        "gps": null,
                        "mediaId": 2,
                        "timestampText": "00:34:36"
                    },
                    {
                        "id": 58,
                        "timestamp": 2336,
                        "segmentTitle": "Arrived to Germany",
                        "partialTranscription": "How did you feel yourself?",
                        "keywords": "Support; Safe; Life; Asylum process; no information; Appeal; Help; Lawyer; Organisation; Community; Reunion; Boyfriend; Not safe; Azul Home; Refugee Detention Centre; Fear; Safe house; Colone; Happy;",
                        "subject": null,
                        "synopsis": null,
                        "gps": null,
                        "mediaId": 2,
                        "timestampText": "00:38:56"
                    },
                    {
                        "id": 59,
                        "timestamp": 2878,
                        "segmentTitle": "Settling in a new country",
                        "partialTranscription": "What was your experience of settling in a new country?",
                        "keywords": "Safe; Plans; Support LGBT community, Homosexual; Freedom; Documents; Stress; Good people; Diversity;",
                        "subject": null,
                        "synopsis": null,
                        "gps": null,
                        "mediaId": 2,
                        "timestampText": "00:47:58"
                    },
                    {
                        "id": 60,
                        "timestamp": 3288,
                        "segmentTitle": "Community support",
                        "partialTranscription": "Do you have friends here?",
                        "keywords": "Peer-support, Meetings, Fun, Best Friend, LGBT community, Identity;",
                        "subject": null,
                        "synopsis": null,
                        "gps": null,
                        "mediaId": 2,
                        "timestampText": "00:54:48"
                    },
                    {
                        "id": 61,
                        "timestamp": 3602,
                        "segmentTitle": "Homophobia in Germany",
                        "partialTranscription": "In Bangladesh, you lived a closed life because it was risky for you. After living some time in Germany is it easy to say now that you are gay?",
                        "keywords": "racism; negative; bulling; safety, gay, schwul; public transport; public place; clothes, style,",
                        "subject": null,
                        "synopsis": null,
                        "gps": null,
                        "mediaId": 2,
                        "timestampText": "01:00:02"
                    },
                    {
                        "id": 62,
                        "timestamp": 3936,
                        "segmentTitle": "German LGBTIQ community",
                        "partialTranscription": "Do you feel that you are part of German LGBTIQ community?",
                        "keywords": "Belonging; Give back; Support;",
                        "subject": null,
                        "synopsis": null,
                        "gps": null,
                        "mediaId": 2,
                        "timestampText": "01:05:36"
                    },
                    {
                        "id": 63,
                        "timestamp": 3995,
                        "segmentTitle": "Learning the German Language",
                        "partialTranscription": "Could you speak German when you came here? What was your experience finding a job?",
                        "keywords": "Language school; Government support; Visa restriction; Work permit; Hospitality; Cook; Deportation;",
                        "subject": null,
                        "synopsis": null,
                        "gps": null,
                        "mediaId": 2,
                        "timestampText": "01:06:35"
                    },
                    {
                        "id": 64,
                        "timestamp": 4251,
                        "segmentTitle": "Hopes for the future",
                        "partialTranscription": "What are your dreams for the future?",
                        "keywords": null,
                        "subject": null,
                        "synopsis": null,
                        "gps": null,
                        "mediaId": 2,
                        "timestampText": "01:10:51"
                    },
                    {
                        "id": 65,
                        "timestamp": 4404,
                        "segmentTitle": "Final thoughts",
                        "partialTranscription": "Would you like to add anything to this interview?",
                        "keywords": null,
                        "subject": null,
                        "synopsis": null,
                        "gps": null,
                        "mediaId": 2,
                        "timestampText": "01:13:24"
                    },
                    {
                        "id": 66,
                        "timestamp": 2,
                        "segmentTitle": "Personal background",
                        "partialTranscription": "Could you please tell me about your background?",
                        "keywords": "Bangladesh; Germany; Middle East; Iraq; Father; Protection; Safety; Turkey; Europe; Boat; Syria; Sexual orientation; Gay; Homosexual",
                        "subject": "test5",
                        "synopsis": "test0",
                        "gps": "33.8496¡ S, 151.2140¡ E",
                        "mediaId": 2,
                        "timestampText": "00:00:02"
                    },
                    {
                        "id": 67,
                        "timestamp": 63,
                        "segmentTitle": "Childhood",
                        "partialTranscription": "You said that your father could not protect you every time, and you do not feel safe. Could you tell more about this?",
                        "keywords": "Girls; Friend; Different; This way; Tenth grade; Boyfriend; gay; Sister; Religious family; Pressure;",
                        "subject": null,
                        "synopsis": null,
                        "gps": null,
                        "mediaId": 2,
                        "timestampText": "00:01:03"
                    },
                    {
                        "id": 68,
                        "timestamp": 270,
                        "segmentTitle": "Coming out",
                        "partialTranscription": "What do you remember about how your friends and parents reacted to your coming out?",
                        "keywords": "Religious family; Pressure; Domestic and family violence; No protection; Pressure; Marriage; Control; Earring; Clothes; Stigma; Love; Social Media;",
                        "subject": null,
                        "synopsis": null,
                        "gps": null,
                        "mediaId": 2,
                        "timestampText": "00:04:30"
                    },
                    {
                        "id": 69,
                        "timestamp": 840,
                        "segmentTitle": "First relationship",
                        "partialTranscription": "Your first boyfriend happened when you were in the 10th grade?",
                        "keywords": "Fourteen years, Naughty, hugs, Family; Beating; Threats; Not safe;",
                        "subject": null,
                        "synopsis": null,
                        "gps": null,
                        "mediaId": 2,
                        "timestampText": "00:14:00"
                    },
                    {
                        "id": 70,
                        "timestamp": 1025,
                        "segmentTitle": "LGBTIQ community",
                        "partialTranscription": "Did you have any organizations that worked with LGBTIQ community back where you lived?",
                        "keywords": "Young; School; Stress; LGBT; Not safe; Unknown man; Left country, India; Pakistan; Iran; Turkey; Iraq; Travel; Friend, Organisation; Help;",
                        "subject": null,
                        "synopsis": null,
                        "gps": null,
                        "mediaId": 2,
                        "timestampText": "00:17:05"
                    },
                    {
                        "id": 71,
                        "timestamp": 1342,
                        "segmentTitle": "LGBTIQ community in Germany",
                        "partialTranscription": "Were you active in the LGBTIQ movement?",
                        "keywords": "Help; Minority; Homophobia; LGBT; Support; Freedom; Government, Problems, Solutions;",
                        "subject": null,
                        "synopsis": null,
                        "gps": null,
                        "mediaId": 2,
                        "timestampText": "00:22:22"
                    },
                    {
                        "id": 72,
                        "timestamp": 1570,
                        "segmentTitle": "LGBTIQ community in Bangladesh",
                        "partialTranscription": "You were not involved in activism in Bangladesh?",
                        "keywords": "Violence; Verbal abuse; Friends; Community; Terrorist; Killed; Xulhaz Mannan;  LGBT activist;",
                        "subject": null,
                        "synopsis": null,
                        "gps": null,
                        "mediaId": 2,
                        "timestampText": "00:26:10"
                    },
                    {
                        "id": 73,
                        "timestamp": 1785,
                        "segmentTitle": "Relationship with family",
                        "partialTranscription": "Did you have the last event that you said to yourself  that is it. I cannot take more of life like this, I am leaving",
                        "keywords": "Uncle; Threats; Physical violence; Move on; Rejection; Discrimination; Sister; Relationship; Mental health; neighbours; aggressive; Leave",
                        "subject": null,
                        "synopsis": null,
                        "gps": null,
                        "mediaId": 2,
                        "timestampText": "00:29:45"
                    },
                    {
                        "id": 74,
                        "timestamp": 2076,
                        "segmentTitle": "Escape from country",
                        "partialTranscription": "How did you end up in Germany?",
                        "keywords": "Plan; Father; Support; Iraq; Like a person; Alone; Cousin; Turkey; Germany; Walk; Boat; Syrian people; Greece; Hunger;",
                        "subject": null,
                        "synopsis": null,
                        "gps": null,
                        "mediaId": 2,
                        "timestampText": "00:34:36"
                    },
                    {
                        "id": 75,
                        "timestamp": 2336,
                        "segmentTitle": "Arrived to Germany",
                        "partialTranscription": "How did you feel yourself?",
                        "keywords": "Support; Safe; Life; Asylum process; no information; Appeal; Help; Lawyer; Organisation; Community; Reunion; Boyfriend; Not safe; Azul Home; Refugee Detention Centre; Fear; Safe house; Colone; Happy;",
                        "subject": null,
                        "synopsis": null,
                        "gps": null,
                        "mediaId": 2,
                        "timestampText": "00:38:56"
                    },
                    {
                        "id": 76,
                        "timestamp": 2878,
                        "segmentTitle": "Settling in a new country",
                        "partialTranscription": "What was your experience of settling in a new country?",
                        "keywords": "Safe; Plans; Support LGBT community, Homosexual; Freedom; Documents; Stress; Good people; Diversity;",
                        "subject": null,
                        "synopsis": null,
                        "gps": null,
                        "mediaId": 2,
                        "timestampText": "00:47:58"
                    },
                    {
                        "id": 77,
                        "timestamp": 3288,
                        "segmentTitle": "Community support",
                        "partialTranscription": "Do you have friends here?",
                        "keywords": "Peer-support, Meetings, Fun, Best Friend, LGBT community, Identity;",
                        "subject": null,
                        "synopsis": null,
                        "gps": null,
                        "mediaId": 2,
                        "timestampText": "00:54:48"
                    },
                    {
                        "id": 78,
                        "timestamp": 3602,
                        "segmentTitle": "Homophobia in Germany",
                        "partialTranscription": "In Bangladesh, you lived a closed life because it was risky for you. After living some time in Germany is it easy to say now that you are gay?",
                        "keywords": "racism; negative; bulling; safety, gay, schwul; public transport; public place; clothes, style,",
                        "subject": null,
                        "synopsis": null,
                        "gps": null,
                        "mediaId": 2,
                        "timestampText": "01:00:02"
                    },
                    {
                        "id": 79,
                        "timestamp": 3936,
                        "segmentTitle": "German LGBTIQ community",
                        "partialTranscription": "Do you feel that you are part of German LGBTIQ community?",
                        "keywords": "Belonging; Give back; Support;",
                        "subject": null,
                        "synopsis": null,
                        "gps": null,
                        "mediaId": 2,
                        "timestampText": "01:05:36"
                    },
                    {
                        "id": 80,
                        "timestamp": 3995,
                        "segmentTitle": "Learning the German Language",
                        "partialTranscription": "Could you speak German when you came here? What was your experience finding a job?",
                        "keywords": "Language school; Government support; Visa restriction; Work permit; Hospitality; Cook; Deportation;",
                        "subject": null,
                        "synopsis": null,
                        "gps": null,
                        "mediaId": 2,
                        "timestampText": "01:06:35"
                    },
                    {
                        "id": 81,
                        "timestamp": 4251,
                        "segmentTitle": "Hopes for the future",
                        "partialTranscription": "What are your dreams for the future?",
                        "keywords": null,
                        "subject": null,
                        "synopsis": null,
                        "gps": null,
                        "mediaId": 2,
                        "timestampText": "01:10:51"
                    },
                    {
                        "id": 82,
                        "timestamp": 4404,
                        "segmentTitle": "Final thoughts",
                        "partialTranscription": "Would you like to add anything to this interview?",
                        "keywords": null,
                        "subject": null,
                        "synopsis": null,
                        "gps": null,
                        "mediaId": 2,
                        "timestampText": "01:13:24"
                    },
                    {
                        "id": 83,
                        "timestamp": 2,
                        "segmentTitle": "Personal background",
                        "partialTranscription": "Could you please tell me about your background?",
                        "keywords": "Bangladesh; Germany; Middle East; Iraq; Father; Protection; Safety; Turkey; Europe; Boat; Syria; Sexual orientation; Gay; Homosexual",
                        "subject": "test5",
                        "synopsis": "test6",
                        "gps": "33.8496¡ S, 151.2140¡ E",
                        "mediaId": 2,
                        "timestampText": "00:00:02"
                    },
                    {
                        "id": 84,
                        "timestamp": 63,
                        "segmentTitle": "Childhood",
                        "partialTranscription": "You said that your father could not protect you every time, and you do not feel safe. Could you tell more about this?",
                        "keywords": "Girls; Friend; Different; This way; Tenth grade; Boyfriend; gay; Sister; Religious family; Pressure;",
                        "subject": "test10",
                        "synopsis": "test11",
                        "gps": null,
                        "mediaId": 2,
                        "timestampText": "00:01:03"
                    },
                    {
                        "id": 85,
                        "timestamp": 270,
                        "segmentTitle": "Coming out",
                        "partialTranscription": "What do you remember about how your friends and parents reacted to your coming out?",
                        "keywords": "Religious family; Pressure; Domestic and family violence; No protection; Pressure; Marriage; Control; Earring; Clothes; Stigma; Love; Social Media;",
                        "subject": null,
                        "synopsis": null,
                        "gps": null,
                        "mediaId": 2,
                        "timestampText": "00:04:30"
                    },
                    {
                        "id": 86,
                        "timestamp": 840,
                        "segmentTitle": "First relationship",
                        "partialTranscription": "Your first boyfriend happened when you were in the 10th grade?",
                        "keywords": "Fourteen years, Naughty, hugs, Family; Beating; Threats; Not safe;",
                        "subject": null,
                        "synopsis": null,
                        "gps": null,
                        "mediaId": 2,
                        "timestampText": "00:14:00"
                    },
                    {
                        "id": 87,
                        "timestamp": 1025,
                        "segmentTitle": "LGBTIQ community",
                        "partialTranscription": "Did you have any organizations that worked with LGBTIQ community back where you lived?",
                        "keywords": "Young; School; Stress; LGBT; Not safe; Unknown man; Left country, India; Pakistan; Iran; Turkey; Iraq; Travel; Friend, Organisation; Help;",
                        "subject": null,
                        "synopsis": null,
                        "gps": null,
                        "mediaId": 2,
                        "timestampText": "00:17:05"
                    },
                    {
                        "id": 88,
                        "timestamp": 1342,
                        "segmentTitle": "LGBTIQ community in Germany",
                        "partialTranscription": "Were you active in the LGBTIQ movement?",
                        "keywords": "Help; Minority; Homophobia; LGBT; Support; Freedom; Government, Problems, Solutions;",
                        "subject": null,
                        "synopsis": null,
                        "gps": null,
                        "mediaId": 2,
                        "timestampText": "00:22:22"
                    },
                    {
                        "id": 89,
                        "timestamp": 1570,
                        "segmentTitle": "LGBTIQ community in Bangladesh",
                        "partialTranscription": "You were not involved in activism in Bangladesh?",
                        "keywords": "Violence; Verbal abuse; Friends; Community; Terrorist; Killed; Xulhaz Mannan;  LGBT activist;",
                        "subject": null,
                        "synopsis": null,
                        "gps": null,
                        "mediaId": 2,
                        "timestampText": "00:26:10"
                    },
                    {
                        "id": 90,
                        "timestamp": 1785,
                        "segmentTitle": "Relationship with family",
                        "partialTranscription": "Did you have the last event that you said to yourself  that is it. I cannot take more of life like this, I am leaving",
                        "keywords": "Uncle; Threats; Physical violence; Move on; Rejection; Discrimination; Sister; Relationship; Mental health; neighbours; aggressive; Leave",
                        "subject": null,
                        "synopsis": null,
                        "gps": null,
                        "mediaId": 2,
                        "timestampText": "00:29:45"
                    },
                    {
                        "id": 91,
                        "timestamp": 2076,
                        "segmentTitle": "Escape from country",
                        "partialTranscription": "How did you end up in Germany?",
                        "keywords": "Plan; Father; Support; Iraq; Like a person; Alone; Cousin; Turkey; Germany; Walk; Boat; Syrian people; Greece; Hunger;",
                        "subject": null,
                        "synopsis": null,
                        "gps": null,
                        "mediaId": 2,
                        "timestampText": "00:34:36"
                    },
                    {
                        "id": 92,
                        "timestamp": 2336,
                        "segmentTitle": "Arrived to Germany",
                        "partialTranscription": "How did you feel yourself?",
                        "keywords": "Support; Safe; Life; Asylum process; no information; Appeal; Help; Lawyer; Organisation; Community; Reunion; Boyfriend; Not safe; Azul Home; Refugee Detention Centre; Fear; Safe house; Colone; Happy;",
                        "subject": null,
                        "synopsis": null,
                        "gps": null,
                        "mediaId": 2,
                        "timestampText": "00:38:56"
                    },
                    {
                        "id": 93,
                        "timestamp": 2878,
                        "segmentTitle": "Settling in a new country",
                        "partialTranscription": "What was your experience of settling in a new country?",
                        "keywords": "Safe; Plans; Support LGBT community, Homosexual; Freedom; Documents; Stress; Good people; Diversity;",
                        "subject": null,
                        "synopsis": null,
                        "gps": null,
                        "mediaId": 2,
                        "timestampText": "00:47:58"
                    },
                    {
                        "id": 94,
                        "timestamp": 3288,
                        "segmentTitle": "Community support",
                        "partialTranscription": "Do you have friends here?",
                        "keywords": "Peer-support, Meetings, Fun, Best Friend, LGBT community, Identity;",
                        "subject": null,
                        "synopsis": null,
                        "gps": null,
                        "mediaId": 2,
                        "timestampText": "00:54:48"
                    },
                    {
                        "id": 95,
                        "timestamp": 3602,
                        "segmentTitle": "Homophobia in Germany",
                        "partialTranscription": "In Bangladesh, you lived a closed life because it was risky for you. After living some time in Germany is it easy to say now that you are gay?",
                        "keywords": "racism; negative; bulling; safety, gay, schwul; public transport; public place; clothes, style,",
                        "subject": null,
                        "synopsis": null,
                        "gps": null,
                        "mediaId": 2,
                        "timestampText": "01:00:02"
                    },
                    {
                        "id": 96,
                        "timestamp": 3936,
                        "segmentTitle": "German LGBTIQ community",
                        "partialTranscription": "Do you feel that you are part of German LGBTIQ community?",
                        "keywords": "Belonging; Give back; Support;",
                        "subject": null,
                        "synopsis": null,
                        "gps": null,
                        "mediaId": 2,
                        "timestampText": "01:05:36"
                    },
                    {
                        "id": 97,
                        "timestamp": 3995,
                        "segmentTitle": "Learning the German Language",
                        "partialTranscription": "Could you speak German when you came here? What was your experience finding a job?",
                        "keywords": "Language school; Government support; Visa restriction; Work permit; Hospitality; Cook; Deportation;",
                        "subject": null,
                        "synopsis": null,
                        "gps": null,
                        "mediaId": 2,
                        "timestampText": "01:06:35"
                    },
                    {
                        "id": 98,
                        "timestamp": 4251,
                        "segmentTitle": "Hopes for the future",
                        "partialTranscription": "What are your dreams for the future?",
                        "keywords": null,
                        "subject": null,
                        "synopsis": null,
                        "gps": null,
                        "mediaId": 2,
                        "timestampText": "01:10:51"
                    },
                    {
                        "id": 99,
                        "timestamp": 4404,
                        "segmentTitle": "Final thoughts",
                        "partialTranscription": "Would you like to add anything to this interview?",
                        "keywords": null,
                        "subject": null,
                        "synopsis": null,
                        "gps": null,
                        "mediaId": 2,
                        "timestampText": "01:13:24"
                    },
                    {
                        "id": 100,
                        "timestamp": 2,
                        "segmentTitle": "Personal background",
                        "partialTranscription": "Could you please tell me about your background?",
                        "keywords": "Bangladesh; Germany; Middle East; Iraq; Father; Protection; Safety; Turkey; Europe; Boat; Syria; Sexual orientation; Gay; Homosexual",
                        "subject": "test5",
                        "synopsis": "test6",
                        "gps": "33.8496¡ S, 151.2140¡ E",
                        "mediaId": 2,
                        "timestampText": "00:00:02"
                    },
                    {
                        "id": 101,
                        "timestamp": 63,
                        "segmentTitle": "Childhood",
                        "partialTranscription": "You said that your father could not protect you every time, and you do not feel safe. Could you tell more about this?",
                        "keywords": "Girls; Friend; Different; This way; Tenth grade; Boyfriend; gay; Sister; Religious family; Pressure;",
                        "subject": "test10",
                        "synopsis": "test11",
                        "gps": null,
                        "mediaId": 2,
                        "timestampText": "00:01:03"
                    },
                    {
                        "id": 102,
                        "timestamp": 270,
                        "segmentTitle": "Coming out",
                        "partialTranscription": "What do you remember about how your friends and parents reacted to your coming out?",
                        "keywords": "Religious family; Pressure; Domestic and family violence; No protection; Pressure; Marriage; Control; Earring; Clothes; Stigma; Love; Social Media;",
                        "subject": null,
                        "synopsis": null,
                        "gps": null,
                        "mediaId": 2,
                        "timestampText": "00:04:30"
                    },
                    {
                        "id": 103,
                        "timestamp": 840,
                        "segmentTitle": "First relationship",
                        "partialTranscription": "Your first boyfriend happened when you were in the 10th grade?",
                        "keywords": "Fourteen years, Naughty, hugs, Family; Beating; Threats; Not safe;",
                        "subject": null,
                        "synopsis": null,
                        "gps": null,
                        "mediaId": 2,
                        "timestampText": "00:14:00"
                    },
                    {
                        "id": 104,
                        "timestamp": 1025,
                        "segmentTitle": "LGBTIQ community",
                        "partialTranscription": "Did you have any organizations that worked with LGBTIQ community back where you lived?",
                        "keywords": "Young; School; Stress; LGBT; Not safe; Unknown man; Left country, India; Pakistan; Iran; Turkey; Iraq; Travel; Friend, Organisation; Help;",
                        "subject": null,
                        "synopsis": null,
                        "gps": null,
                        "mediaId": 2,
                        "timestampText": "00:17:05"
                    },
                    {
                        "id": 105,
                        "timestamp": 1342,
                        "segmentTitle": "LGBTIQ community in Germany",
                        "partialTranscription": "Were you active in the LGBTIQ movement?",
                        "keywords": "Help; Minority; Homophobia; LGBT; Support; Freedom; Government, Problems, Solutions;",
                        "subject": null,
                        "synopsis": null,
                        "gps": null,
                        "mediaId": 2,
                        "timestampText": "00:22:22"
                    },
                    {
                        "id": 106,
                        "timestamp": 1570,
                        "segmentTitle": "LGBTIQ community in Bangladesh",
                        "partialTranscription": "You were not involved in activism in Bangladesh?",
                        "keywords": "Violence; Verbal abuse; Friends; Community; Terrorist; Killed; Xulhaz Mannan;  LGBT activist;",
                        "subject": null,
                        "synopsis": null,
                        "gps": null,
                        "mediaId": 2,
                        "timestampText": "00:26:10"
                    },
                    {
                        "id": 107,
                        "timestamp": 1785,
                        "segmentTitle": "Relationship with family",
                        "partialTranscription": "Did you have the last event that you said to yourself  that is it. I cannot take more of life like this, I am leaving",
                        "keywords": "Uncle; Threats; Physical violence; Move on; Rejection; Discrimination; Sister; Relationship; Mental health; neighbours; aggressive; Leave",
                        "subject": null,
                        "synopsis": null,
                        "gps": null,
                        "mediaId": 2,
                        "timestampText": "00:29:45"
                    },
                    {
                        "id": 108,
                        "timestamp": 2076,
                        "segmentTitle": "Escape from country",
                        "partialTranscription": "How did you end up in Germany?",
                        "keywords": "Plan; Father; Support; Iraq; Like a person; Alone; Cousin; Turkey; Germany; Walk; Boat; Syrian people; Greece; Hunger;",
                        "subject": null,
                        "synopsis": null,
                        "gps": null,
                        "mediaId": 2,
                        "timestampText": "00:34:36"
                    },
                    {
                        "id": 109,
                        "timestamp": 2336,
                        "segmentTitle": "Arrived to Germany",
                        "partialTranscription": "How did you feel yourself?",
                        "keywords": "Support; Safe; Life; Asylum process; no information; Appeal; Help; Lawyer; Organisation; Community; Reunion; Boyfriend; Not safe; Azul Home; Refugee Detention Centre; Fear; Safe house; Colone; Happy;",
                        "subject": null,
                        "synopsis": null,
                        "gps": null,
                        "mediaId": 2,
                        "timestampText": "00:38:56"
                    },
                    {
                        "id": 110,
                        "timestamp": 2878,
                        "segmentTitle": "Settling in a new country",
                        "partialTranscription": "What was your experience of settling in a new country?",
                        "keywords": "Safe; Plans; Support LGBT community, Homosexual; Freedom; Documents; Stress; Good people; Diversity;",
                        "subject": null,
                        "synopsis": null,
                        "gps": null,
                        "mediaId": 2,
                        "timestampText": "00:47:58"
                    },
                    {
                        "id": 111,
                        "timestamp": 3288,
                        "segmentTitle": "Community support",
                        "partialTranscription": "Do you have friends here?",
                        "keywords": "Peer-support, Meetings, Fun, Best Friend, LGBT community, Identity;",
                        "subject": null,
                        "synopsis": null,
                        "gps": null,
                        "mediaId": 2,
                        "timestampText": "00:54:48"
                    },
                    {
                        "id": 112,
                        "timestamp": 3602,
                        "segmentTitle": "Homophobia in Germany",
                        "partialTranscription": "In Bangladesh, you lived a closed life because it was risky for you. After living some time in Germany is it easy to say now that you are gay?",
                        "keywords": "racism; negative; bulling; safety, gay, schwul; public transport; public place; clothes, style,",
                        "subject": null,
                        "synopsis": null,
                        "gps": null,
                        "mediaId": 2,
                        "timestampText": "01:00:02"
                    },
                    {
                        "id": 113,
                        "timestamp": 3936,
                        "segmentTitle": "German LGBTIQ community",
                        "partialTranscription": "Do you feel that you are part of German LGBTIQ community?",
                        "keywords": "Belonging; Give back; Support;",
                        "subject": null,
                        "synopsis": null,
                        "gps": null,
                        "mediaId": 2,
                        "timestampText": "01:05:36"
                    },
                    {
                        "id": 114,
                        "timestamp": 3995,
                        "segmentTitle": "Learning the German Language",
                        "partialTranscription": "Could you speak German when you came here? What was your experience finding a job?",
                        "keywords": "Language school; Government support; Visa restriction; Work permit; Hospitality; Cook; Deportation;",
                        "subject": null,
                        "synopsis": null,
                        "gps": null,
                        "mediaId": 2,
                        "timestampText": "01:06:35"
                    },
                    {
                        "id": 115,
                        "timestamp": 4251,
                        "segmentTitle": "Hopes for the future",
                        "partialTranscription": "What are your dreams for the future?",
                        "keywords": null,
                        "subject": null,
                        "synopsis": null,
                        "gps": null,
                        "mediaId": 2,
                        "timestampText": "01:10:51"
                    },
                    {
                        "id": 116,
                        "timestamp": 4404,
                        "segmentTitle": "Final thoughts",
                        "partialTranscription": "Would you like to add anything to this interview?",
                        "keywords": null,
                        "subject": null,
                        "synopsis": null,
                        "gps": null,
                        "mediaId": 2,
                        "timestampText": "01:13:24"
                    }
                ]
            },
            {
                "id": 13,
                "accessName": "AQDA_2019-06-21_0001_AS_DE-P",
                "status": 1,
                "accessionDate": "2007-01-22",
                "youtubeUrl": "",
                "interviewId": 2,
                "mediaType": 1,
                "size": null,
                "length": 4491,
                "youtubeDes": "",
                "lengthText": "01:14:51",
                "storages": [],
                "transcriptions": []
            }
        ]
    },
    {
        "id": 18,
        "intervieweeLocation": "City, District of Canberra Central, Australian Capital Territory, 2601, Australia",
        "date": "0022-10-20",
        "escapeCountry": "Morocco",
        "transgender": 0,
        "intervieweeId": 6,
        "interviewerId": 1,
        "isCitizen": 0,
        "pseudonym": 0,
        "videoDistortion": 0,
        "voiceChange": 0,
        "contextual": "",
        "refugeeCamp": 0,
        "published": 1,
        "accessionName": "AQDA_2020-09-22_0005_MI_AU",
        "migrationId": 3,
        "lat": "-35.2812678",
        "lng": "149.1291868",
        "genderId": 1,
        "narratorNameD": "Asmaa Guedira",
        "docLink": "",
        "languageId": 1,
        "image": "/aqda/frontend/web/index.php?r=interview/showimage&id=18",
        "narrator": {
            "id": 6,
            "name": "Asmaa Guedira",
            "birthYear": "1986"
        },
        "interviewer": {
            "id": 1,
            "name": "Renee Dixson",
            "bio": ""
        },
        "migration": {
            "id": 3,
            "name": "Migrant"
        },
        "language": {
            "id": 1,
            "name": "English"
        },
        "pronouns": "She/Her/Hers",
        "sexo": "Queer",
        "gender": {
            "id": 1,
            "name": "Female"
        },
        "publishMedia": [
            {
                "id": 14,
                "accessName": "AQDA_2020-09-22_0005_MI_AU-A",
                "status": 0,
                "accessionDate": null,
                "youtubeUrl": "https://youtu.be/9NMMQMRp6PA",
                "interviewId": 18,
                "mediaType": 1,
                "size": 12260,
                "length": 0,
                "youtubeDes": "",
                "lengthText": "00:00:00",
                "storages": [],
                "transcriptions": []
            }
        ]
    },
    {
        "id": 20,
        "intervieweeLocation": "Melbourne, City of Melbourne, Victoria, Australia",
        "date": "2022-01-09",
        "escapeCountry": "Maldives",
        "transgender": 1,
        "intervieweeId": 8,
        "interviewerId": 1,
        "isCitizen": 0,
        "pseudonym": 0,
        "videoDistortion": 0,
        "voiceChange": 0,
        "contextual": "",
        "refugeeCamp": 0,
        "published": 1,
        "accessionName": "AQDA_2022-01-09_0014_AS_MV",
        "migrationId": 1,
        "lat": "-37.8142176",
        "lng": "144.9631608",
        "genderId": 3,
        "narratorNameD": "Eman Ezekiel",
        "docLink": "",
        "languageId": 1,
        "image": "/aqda/frontend/web/index.php?r=interview/showimage&id=20",
        "narrator": {
            "id": 8,
            "name": "Eman Ezekiel",
            "birthYear": "1994"
        },
        "interviewer": {
            "id": 1,
            "name": "Renee Dixson",
            "bio": ""
        },
        "migration": {
            "id": 1,
            "name": "Asylum seeker"
        },
        "language": {
            "id": 1,
            "name": "English"
        },
        "pronouns": "He/Him/His,They/Them/Theirs",
        "sexo": "Plus,Pansexual ",
        "gender": {
            "id": 3,
            "name": "Non-binary"
        },
        "publishMedia": [
            {
                "id": 16,
                "accessName": "AQDA_2022-01-09_0014_AS_MV",
                "status": 0,
                "accessionDate": null,
                "youtubeUrl": "https://youtu.be/_UQY3VG81eg",
                "interviewId": 20,
                "mediaType": 1,
                "size": null,
                "length": 0,
                "youtubeDes": "",
                "lengthText": "00:00:00",
                "storages": [],
                "transcriptions": []
            }
        ]
    },
    {
        "id": 21,
        "intervieweeLocation": "Melbourne, City of Melbourne, Victoria, Australia",
        "date": "2022-01-08",
        "escapeCountry": "Vietnam",
        "transgender": 0,
        "intervieweeId": 9,
        "interviewerId": 1,
        "isCitizen": 0,
        "pseudonym": 0,
        "videoDistortion": 0,
        "voiceChange": 0,
        "contextual": "",
        "refugeeCamp": 0,
        "published": 1,
        "accessionName": "AQDA_2022-01-08_0013_AS_VN",
        "migrationId": 1,
        "lat": "-37.8142176",
        "lng": "144.9631608",
        "genderId": 2,
        "narratorNameD": "Tristan",
        "docLink": "",
        "languageId": 1,
        "image": "/aqda/frontend/web/index.php?r=interview/showimage&id=21",
        "narrator": {
            "id": 9,
            "name": "Tristan",
            "birthYear": "1988"
        },
        "interviewer": {
            "id": 1,
            "name": "Renee Dixson",
            "bio": ""
        },
        "migration": {
            "id": 1,
            "name": "Asylum seeker"
        },
        "language": {
            "id": 1,
            "name": "English"
        },
        "pronouns": "He/Him/His",
        "sexo": "Gay",
        "gender": {
            "id": 2,
            "name": "Male"
        },
        "publishMedia": [
            {
                "id": 17,
                "accessName": "AQDA_2022-01-08_0013_AS_VN",
                "status": 1,
                "accessionDate": null,
                "youtubeUrl": "https://youtu.be/Ou1_WvuLjPU",
                "interviewId": 21,
                "mediaType": 1,
                "size": null,
                "length": 0,
                "youtubeDes": "",
                "lengthText": "00:00:00",
                "storages": [],
                "transcriptions": []
            }
        ]
    },
    {
        "id": 22,
        "intervieweeLocation": "Sydney, Council of the City of Sydney, New South Wales, Australia",
        "date": "2021-05-25",
        "escapeCountry": "Africa",
        "transgender": 0,
        "intervieweeId": 10,
        "interviewerId": 1,
        "isCitizen": 0,
        "pseudonym": 1,
        "videoDistortion": 0,
        "voiceChange": 1,
        "contextual": "",
        "refugeeCamp": 0,
        "published": 1,
        "accessionName": "AQDA_2021-05-26_0009_AS_AU",
        "migrationId": 1,
        "lat": "-33.8698439",
        "lng": "151.2082848",
        "genderId": 1,
        "narratorNameD": "Victor",
        "docLink": "",
        "languageId": 1,
        "image": "/aqda/frontend/web/index.php?r=interview/showimage&id=22",
        "narrator": {
            "id": 10,
            "name": "Victor",
            "birthYear": "1971"
        },
        "interviewer": {
            "id": 1,
            "name": "Renee Dixson",
            "bio": ""
        },
        "migration": {
            "id": 1,
            "name": "Asylum seeker"
        },
        "language": {
            "id": 1,
            "name": "English"
        },
        "pronouns": "She/Her/Hers",
        "sexo": "Queer",
        "gender": {
            "id": 1,
            "name": "Female"
        },
        "publishMedia": [
            {
                "id": 18,
                "accessName": "AQDA_2021-05-26_0009_AS_AU",
                "status": 1,
                "accessionDate": null,
                "youtubeUrl": "https://youtu.be/S_t0e89ZCxQ",
                "interviewId": 22,
                "mediaType": 1,
                "size": null,
                "length": 0,
                "youtubeDes": "",
                "lengthText": "00:00:00",
                "storages": [],
                "transcriptions": []
            }
        ]
    },
    {
        "id": 23,
        "intervieweeLocation": "Sydney, Council of the City of Sydney, New South Wales, Australia",
        "date": "2021-06-14",
        "escapeCountry": "Iran",
        "transgender": 1,
        "intervieweeId": 11,
        "interviewerId": 1,
        "isCitizen": 0,
        "pseudonym": 1,
        "videoDistortion": 0,
        "voiceChange": 1,
        "contextual": "",
        "refugeeCamp": 0,
        "published": 1,
        "accessionName": "AQDA_2021-06-14_0010_RE_IR",
        "migrationId": 2,
        "lat": "-33.8698439",
        "lng": "151.2082848",
        "genderId": 1,
        "narratorNameD": "Gabriella",
        "docLink": "",
        "languageId": 1,
        "image": "/aqda/frontend/web/index.php?r=interview/showimage&id=23",
        "narrator": {
            "id": 11,
            "name": "Gabriella",
            "birthYear": "1985"
        },
        "interviewer": {
            "id": 1,
            "name": "Renee Dixson",
            "bio": ""
        },
        "migration": {
            "id": 2,
            "name": "Refugee"
        },
        "language": {
            "id": 1,
            "name": "English"
        },
        "pronouns": "She/Her/Hers",
        "sexo": "Heterosexual",
        "gender": {
            "id": 1,
            "name": "Female"
        },
        "publishMedia": [
            {
                "id": 19,
                "accessName": "AQDA_2021-06-14_0010_RE_IR",
                "status": 1,
                "accessionDate": null,
                "youtubeUrl": "https://youtu.be/DZxX94m9oes",
                "interviewId": 23,
                "mediaType": 1,
                "size": null,
                "length": 0,
                "youtubeDes": "",
                "lengthText": "00:00:00",
                "storages": [],
                "transcriptions": []
            }
        ]
    },
    {
        "id": 24,
        "intervieweeLocation": "Monheim am Rhein, Kreis Mettmann, North Rhine-Westphalia, 40789, Germany",
        "date": "2019-06-21",
        "escapeCountry": "Ukraine",
        "transgender": 1,
        "intervieweeId": 12,
        "interviewerId": 1,
        "isCitizen": 0,
        "pseudonym": 0,
        "videoDistortion": 0,
        "voiceChange": 0,
        "contextual": "",
        "refugeeCamp": 0,
        "published": 1,
        "accessionName": "AQDA_2019-06-21_0002_AS_UA",
        "migrationId": 1,
        "lat": "51.0908881",
        "lng": "6.8832264",
        "genderId": 3,
        "narratorNameD": "Vald | Shylova Kateryna",
        "docLink": "",
        "languageId": 2,
        "image": "/aqda/frontend/web/index.php?r=interview/showimage&id=24",
        "narrator": {
            "id": 12,
            "name": "Vald | Shylova Kateryna",
            "birthYear": "1996"
        },
        "interviewer": {
            "id": 1,
            "name": "Renee Dixson",
            "bio": ""
        },
        "migration": {
            "id": 1,
            "name": "Asylum seeker"
        },
        "language": {
            "id": 2,
            "name": "Russian"
        },
        "pronouns": "She/Her/Hers,He/Him/His,They/Them/Theirs",
        "sexo": "Lesbian,Plus,Pansexual ",
        "gender": {
            "id": 3,
            "name": "Non-binary"
        },
        "publishMedia": [
            {
                "id": 20,
                "accessName": "AQDA_2019-06-21_0002_AS_UA",
                "status": 1,
                "accessionDate": null,
                "youtubeUrl": "https://youtu.be/3JXDsWFjthQ",
                "interviewId": 24,
                "mediaType": 1,
                "size": null,
                "length": 0,
                "youtubeDes": "",
                "lengthText": "00:00:00",
                "storages": [],
                "transcriptions": []
            }
        ]
    }
]

export default apiData;